## Create a Game

In [1]:
import nashpy as nash
import numpy as np

### Game Creation

In [2]:
A = np.array([[0, -1, 1], [1, 0, -1], [-1, 1, 0]])
rps = nash.Game(A)
rps

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

### Payoffs of a game

In [4]:
#Play of the row player (means he plays the 3rd row)
sigma_r = [0, 0, 1]
#Play of the column player (means he plays the 2nd col)
sigma_c = [0, 1, 0]
#Calculate pay-off
rps[sigma_r, sigma_c]

#Results gives the pay-off for the row player first and then for the col player

array([ 1, -1])

In [5]:
sigma_c = [1 / 2, 1 / 2, 0]
sigma_r = [0, 1 / 2, 1 / 2]
rps[sigma_r, sigma_c]

array([ 0.25, -0.25])

### Nash Equilibrium

In [6]:
eqs = rps.support_enumeration()
list(eqs)

[(array([0.33333333, 0.33333333, 0.33333333]),
  array([0.33333333, 0.33333333, 0.33333333]))]

In [8]:
rps

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

In [7]:
iterations = 100
np.random.seed(0)
play_counts = rps.fictitious_play(iterations=iterations)
for row_play_count, column_play_count in play_counts:
    print(row_play_count, column_play_count)

[0 0 0] [0 0 0]
[1. 0. 0.] [0. 1. 0.]
[1. 0. 1.] [0. 2. 0.]
[1. 0. 2.] [1. 2. 0.]
[1. 1. 2.] [2. 2. 0.]
[1. 2. 2.] [3. 2. 0.]
[1. 3. 2.] [3. 2. 1.]
[1. 4. 2.] [3. 2. 2.]
[1. 5. 2.] [3. 2. 3.]
[2. 5. 2.] [3. 2. 4.]
[3. 5. 2.] [3. 2. 5.]
[4. 5. 2.] [3. 2. 6.]
[5. 5. 2.] [3. 3. 6.]
[6. 5. 2.] [3. 4. 6.]
[7. 5. 2.] [3. 5. 6.]
[7. 5. 3.] [3. 6. 6.]
[7. 5. 4.] [3. 7. 6.]
[7. 5. 5.] [3. 8. 6.]
[7. 5. 6.] [3. 9. 6.]
[7. 5. 7.] [ 3. 10.  6.]
[7. 5. 8.] [ 4. 10.  6.]
[7. 5. 9.] [ 5. 10.  6.]
[ 7.  5. 10.] [ 6. 10.  6.]
[ 7.  5. 11.] [ 7. 10.  6.]
[ 7.  5. 12.] [ 8. 10.  6.]
[ 7.  5. 13.] [ 9. 10.  6.]
[ 7.  6. 13.] [10. 10.  6.]
[ 7.  7. 13.] [11. 10.  6.]
[ 7.  8. 13.] [12. 10.  6.]
[ 7.  9. 13.] [13. 10.  6.]
[ 7. 10. 13.] [14. 10.  6.]
[ 7. 11. 13.] [14. 10.  7.]
[ 7. 12. 13.] [14. 10.  8.]
[ 7. 13. 13.] [14. 10.  9.]
[ 7. 14. 13.] [14. 10. 10.]
[ 7. 15. 13.] [14. 10. 11.]
[ 7. 16. 13.] [14. 10. 12.]
[ 7. 17. 13.] [14. 10. 13.]
[ 8. 17. 13.] [14. 10. 14.]
[ 9. 17. 13.] [14. 10. 15.]
[10. 17. 

In [9]:
A = np.array([[1, -1], [-1, 1]])
matching_pennies = nash.Game(A)

In [14]:
equilibria = matching_pennies.vertex_enumeration()
for eq in equilibria:
    print(eq)

(array([0.5, 0.5]), array([0.5, 0.5]))


In [16]:
list(equilibria)

[]

Lemke Howson

Note that this algorithm is not guaranteed to find all equilibria but is an efficient way of finding an equilibrium.

In [17]:
matching_pennies.lemke_howson(initial_dropped_label=0)

(array([0.5, 0.5]), array([0.5, 0.5]))