## Create a Game

In [2]:
import nashpy as nash
import numpy as np

In [12]:
import pandas as pd

### Matrix Creation
The game is not working. Thus I need to check if it has to do with the extreme low values.

In [9]:
rng = np.random.default_rng(121263137472525314065)
n_rows = 50
n_cols = 50
n_ones = 25

randommatrix = rng.multivariate_hypergeometric([1]*n_cols, n_ones, size=n_rows)
randommatrix

array([[0, 0, 1, ..., 1, 1, 0],
       [1, 1, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 1, 0],
       ...,
       [1, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 1, 1]], dtype=int64)

In [13]:
nredges = len(randommatrix)
gamematrix = pd.DataFrame(np.zeros([nredges, nredges])*np.nan)

In [22]:
randommatrix[1,49]

0

In [23]:
#make a matrix with all the roads
for i in range(0, len(randommatrix)):
    criticalityval = randommatrix[1,i]
    gamematrix.iloc[:,i] = - criticalityval
    gamematrix.iloc[i,i] = criticalityval

In [24]:
gamematrix

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
1  -1.0  1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
2  -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
3  -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
4  -1.0 -1.0  0.0  0.0  1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
5  -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
6  -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
7  -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0  1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
8  -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0  1.0  0.0  ... -1.0  0.0  0.0 -1.0   
9  -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
10 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
11 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
12 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
13 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
14 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
15 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
16 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
17 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
18 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
19 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
20 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
21 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
22 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
23 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
24 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
25 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
26 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
27 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
28 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
29 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
30 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
31 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
32 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
33 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
34 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
35 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
36 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
37 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
38 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
39 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
40 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ...  1.0  0.0  0.0 -1.0   
41 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
42 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
43 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0  1.0   
44 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
45 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
46 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
47 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.0 -1.0 -1.0  0.0  ... -1.0  0.0  0.0 -1.0   
48 -1.0 -1.0  0.0  0.0 -1.0  0.0  0.

### Check if it works for binary Matrix

In [25]:
game = nash.Game(gamematrix)
game

Zero sum game with payoff matrices:

Row player:
[[ 1. -1.  0. ...  0. -1.  0.]
 [-1.  1.  0. ...  0. -1.  0.]
 [-1. -1.  0. ...  0. -1.  0.]
 ...
 [-1. -1.  0. ...  0. -1.  0.]
 [-1. -1.  0. ...  0.  1.  0.]
 [-1. -1.  0. ...  0. -1.  0.]]

Column player:
[[-1.  1. -0. ... -0.  1. -0.]
 [ 1. -1. -0. ... -0.  1. -0.]
 [ 1.  1. -0. ... -0.  1. -0.]
 ...
 [ 1.  1. -0. ... -0.  1. -0.]
 [ 1.  1. -0. ... -0. -1. -0.]
 [ 1.  1. -0. ... -0.  1. -0.]]

In [28]:
# Import time module
import time
 
# record start time
start = time.time()
 
# define a sample code segment
eqs = game.support_enumeration()
list(eqs)
 
# record end time
end = time.time()
 
# print the difference between start
# and end time in milli. secs
print("The time of execution of above program is :",
      (end-start) * 10**3, "ms")

KeyboardInterrupt: 

### Game Creation

In [ ]:
A = np.array([[0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1], [1, 0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1], [-1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1, 0], [0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1], [0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1], [0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1], [1, 0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1], [-1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1, 0], [0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1], [0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1], [0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1], [0, -1, 1, 0, -1, 1, 0, -1, 1, 0, -1, 1]])
rps = nash.Game(A)
rps

In [29]:
emptymatrix = np.load('game_matrixSegou290623.npy')
game = nash.Game(emptymatrix)
game

Bi matrix game with payoff matrices:

Row player:
[[ 3.08686208e-14 -1.30149729e-16 -3.07384711e-14 ... -0.00000000e+00
  -0.00000000e+00 -1.02003377e-16]
 [-3.08686208e-14  1.30149729e-16 -3.07384711e-14 ... -0.00000000e+00
  -0.00000000e+00 -1.02003377e-16]
 [-3.08686208e-14 -1.30149729e-16  3.07384711e-14 ... -0.00000000e+00
  -0.00000000e+00 -1.02003377e-16]
 ...
 [-3.08686208e-14 -1.30149729e-16 -3.07384711e-14 ...  0.00000000e+00
  -0.00000000e+00 -1.02003377e-16]
 [-3.08686208e-14 -1.30149729e-16 -3.07384711e-14 ... -0.00000000e+00
   0.00000000e+00 -1.02003377e-16]
 [-3.08686208e-14 -1.30149729e-16 -3.07384711e-14 ... -0.00000000e+00
  -0.00000000e+00  1.02003377e-16]]

Column player:
[[-3.08686208e-14  1.30149729e-16  3.07384711e-14 ...  0.00000000e+00
   0.00000000e+00  1.02003377e-16]
 [ 3.08686208e-14 -1.30149729e-16  3.07384711e-14 ...  0.00000000e+00
   0.00000000e+00  1.02003377e-16]
 [ 3.08686208e-14  1.30149729e-16 -3.07384711e-14 ...  0.00000000e+00
   0.00000000e+00 

In [36]:
pd.DataFrame(emptymatrix).to_csv("results/testonlinematrix.csv", header=None, index=None, sep=' ')

In [ ]:
eqs = game.support_enumeration()
list(eqs)

In [10]:
eqs = rps.support_enumeration()
list(eqs)

C:\Users\maaik\miniconda3\lib\site-packages\nashpy\algorithms\support_enumeration.py:259: RuntimeWarning: 
An even number of (2048) equilibria was returned. This
indicates that the game is degenerate. Consider using another algorithm
to investigate.
                  
  warnings.warn(warning, RuntimeWarning)


[(array([0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ]),
  array([0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ])),
 (array([0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ]),
  array([0.33333333, 0.33333333, 0.        , 0.        , 0.        ,
         0.33333333, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ])),
 (array([0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ]),
  array([0.33333333, 0.33333333, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.33333333, 0.     

In [12]:
len(eqs)

TypeError: object of type 'generator' has no len()

In [11]:
#3 options
A = np.array([[0, -1, 1], [1, 0, -1], [-1, 1, 0]])
test = nash.Game(A)


eqstest = test.support_enumeration()
list(eqstest)

[(array([0.33333333, 0.33333333, 0.33333333]),
  array([0.33333333, 0.33333333, 0.33333333]))]

In [13]:
test

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

### Payoffs of a game

In [4]:
#Play of the row player (means he plays the 3rd row)
sigma_r = [0, 0, 1]
#Play of the column player (means he plays the 2nd col)
sigma_c = [0, 1, 0]
#Calculate pay-off
rps[sigma_r, sigma_c]

#Results gives the pay-off for the row player first and then for the col player

array([ 1, -1])

In [5]:
sigma_c = [1 / 2, 1 / 2, 0]
sigma_r = [0, 1 / 2, 1 / 2]
rps[sigma_r, sigma_c]

array([ 0.25, -0.25])

### Nash Equilibrium

In [8]:
eqs = rps.support_enumeration()
list(eqs)

[(array([0.33333333, 0.33333333, 0.33333333]),
  array([0.33333333, 0.33333333, 0.33333333]))]

In [8]:
rps

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

In [7]:
iterations = 100
np.random.seed(0)
play_counts = rps.fictitious_play(iterations=iterations)
for row_play_count, column_play_count in play_counts:
    print(row_play_count, column_play_count)

[0 0 0] [0 0 0]
[1. 0. 0.] [0. 1. 0.]
[1. 0. 1.] [0. 2. 0.]
[1. 0. 2.] [1. 2. 0.]
[1. 1. 2.] [2. 2. 0.]
[1. 2. 2.] [3. 2. 0.]
[1. 3. 2.] [3. 2. 1.]
[1. 4. 2.] [3. 2. 2.]
[1. 5. 2.] [3. 2. 3.]
[2. 5. 2.] [3. 2. 4.]
[3. 5. 2.] [3. 2. 5.]
[4. 5. 2.] [3. 2. 6.]
[5. 5. 2.] [3. 3. 6.]
[6. 5. 2.] [3. 4. 6.]
[7. 5. 2.] [3. 5. 6.]
[7. 5. 3.] [3. 6. 6.]
[7. 5. 4.] [3. 7. 6.]
[7. 5. 5.] [3. 8. 6.]
[7. 5. 6.] [3. 9. 6.]
[7. 5. 7.] [ 3. 10.  6.]
[7. 5. 8.] [ 4. 10.  6.]
[7. 5. 9.] [ 5. 10.  6.]
[ 7.  5. 10.] [ 6. 10.  6.]
[ 7.  5. 11.] [ 7. 10.  6.]
[ 7.  5. 12.] [ 8. 10.  6.]
[ 7.  5. 13.] [ 9. 10.  6.]
[ 7.  6. 13.] [10. 10.  6.]
[ 7.  7. 13.] [11. 10.  6.]
[ 7.  8. 13.] [12. 10.  6.]
[ 7.  9. 13.] [13. 10.  6.]
[ 7. 10. 13.] [14. 10.  6.]
[ 7. 11. 13.] [14. 10.  7.]
[ 7. 12. 13.] [14. 10.  8.]
[ 7. 13. 13.] [14. 10.  9.]
[ 7. 14. 13.] [14. 10. 10.]
[ 7. 15. 13.] [14. 10. 11.]
[ 7. 16. 13.] [14. 10. 12.]
[ 7. 17. 13.] [14. 10. 13.]
[ 8. 17. 13.] [14. 10. 14.]
[ 9. 17. 13.] [14. 10. 15.]
[10. 17. 

In [9]:
A = np.array([[1, -1], [-1, 1]])
matching_pennies = nash.Game(A)

In [14]:
equilibria = matching_pennies.vertex_enumeration()
for eq in equilibria:
    print(eq)

(array([0.5, 0.5]), array([0.5, 0.5]))


In [16]:
list(equilibria)

[]

Lemke Howson

Note that this algorithm is not guaranteed to find all equilibria but is an efficient way of finding an equilibrium.

In [17]:
matching_pennies.lemke_howson(initial_dropped_label=0)

(array([0.5, 0.5]), array([0.5, 0.5]))